######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 4 04:04:10 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit
QT += network
QT += openssl

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
